version: "3"
services:
    web:
        image: nginx
        container_name: web
        ports:
            - "80:80"
        volumes:
            - /home/first/my/html:/usr/share/nginx/html
            - /home/first/my/nginx.conf:/etc/nginx/nginx.conf
            - /home/first/my/default.conf:/etc/nginx/conf.d/default.conf
#        networks:
#            net:
#                ipv4_address: 10.100.0.2
    mysql:
       image: mysql
       container_name: mysql 
       ports: 
           - "3306:3306"
       volumes:
           - /home/first/my/data:/var/lib/mysql
           - /home/first/my/mysql:/home
#           - /home/first/my/my.cnf:/etc/mysql/my.cnf
       environment:
           MYSQL_ROOT_PASSWORD: mypassword
#       networks:
#           net:
#               ipv4_address: 10.100.0.3
    php:
       image: php-mysql
       container_name: php 
       ports:
           - "9000:9000"
       volumes:
#           - /home/first/my/www.conf:/usr/local/etc/php-fpm.d/www.conf
           - /home/first/my/php:/var/www/html
#       networks:
#           net:
#               ipv4_address: 10.100.0.4
#networks:
#    net:
#        ipam:
#            config:
#                - subnet: 10.100.0.0/24
